version: '3.9'

services:
  db:
    image: db-image
    container_name: db-container
    restart: on-failure
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_role
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_role"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    image: backend-image
    container_name: backend-container
    restart: on-failure
    build:
      context: ./java-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: frontend-image
    container_name: frontend-container
    restart: on-failure
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
